### ISSUE TITLE
Challenge modifications

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/python-for-everything#29]
- [ ] Simplify challenges into more, smaller tasks
- [ ] Add more exposition at top
- [ ] Add more inline comments explaining keywords and control structures

**Comment by drewhart** [comment]
I agree with all three of these points! A couple others:

1.) Use comment lines to block out sections of code that should/should not be altered or written in.

2.) Keep challenges focused on the main learning objectives (Counter-example: I found 03_analysis/01_json.py frustrating, because its use of a generator was non-essential, overly complicated, and distracted from the main task of learning to index into a Twitter JSON object).

**Comment by deniederhut** [comment]
We're going to call this closed by commits 0f2704b50a327983c6ef1cd0393a66995a1ebc4c through 39ad25651f0ebb9b2858874ee5f0ea40cdb2f4e8 .
