### ISSUE TITLE
Reconsider IDE

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/python-for-everything#31]
Please vote with a comment below -- here are your choices:

* Spyder
* Jupyter

**Comment by akokai** [comment]
Before voting I would like to point out that we are using PyCharm in a way that's much like how you'd use Jupyter notebook -- running individual lines or blocks of code, without having any overall program structure (no `main()`, etc.).

**Comment by matthew-brett** [comment]
I don't know Spyder, but I share the worry of some of you that starting off in the Jupyter notebook very often means that the students continue using the notebook for development, which has many bad consequences, such as poor program structure, less or no testing and undisciplined version control.

**Comment by deniederhut** [comment]
Right. To provide a little bit of context (sorry @matthew-brett , there is a whole separate email thread with our instructors about this), I think both the students and the instructors are finding Rodeo and PyCharm to be buggy enough that it's getting in the way of instruction. Spyder was the least bad, but on Macs have a lag in the UI that grows up to a couple of seconds.

I think the solution might be that we have students explore interactively in jupyter notebooks (e.g. what are all the methods I can call on a string), and that we rewrite the challenges (coding challenges where the students check their progress with pytest) to be small python programs. They'll still need some kind of text editor, but I think the world of text editors that play well with Python is larger than the world of IDEs that do.

**Comment by matthew-brett** [comment]
Can they explore in an IPython console and write in a text editor?   That's what I do in practice.  I sometimes use the `edit` command in the IPython console too?  I mean - do they need an IDE?  I've heard very good things about PyCharm, but otherwise, my impression is that they tend to slow people down after a fairly small amount of experience, compared to a good text editor (Atom etc).

**Comment by drewhart** [comment]
I vote Jupyter.

I personally found PyCharm to be a real pain for a few reasons:
1.) It created problems for some students running certain import statements, because it seemed incapable of dynamically updating the path variable to include the students' Anaconda directory
2.) Its tab completion is really poor, which precludes students' ability to introspect the methods/attributes of objects on the fly, tab-complete paths, etcetera
3.) Font-size increase, highlight-and-evaluate and other simple functionalities seem unncessarily bumpy and/or silly.

After teaching on Thursday, I decidedly lean toward using the Jupyter notebook approach. The notebook's interface takes a few minutes for students to get the hang of (hotkeys, understanding what the cells are and how they work, etc.), but once they do that it is a really solid option. I agree that it could promote poor programming approaches downstream (especially if they continue to work in the notebook in the long-term), but this seems like a secondary concern to me, and one that could be easily headed off by explaining this during workshop and giving some demonstration (perhaps by way of the challenge scripts, which could be run from the Anaconda terminal) of how to write and run a standalone program, and best practices for scripting. I think the primary concerns in a workshop like this are getting students immersed in the language in a clear and non-overwhelming way; giving them a sense of accomplishment and productivity during the in-workshop tasks; demonstrating the potential of programming to improve their research work; and 'hooking' them so that they will continue to study and learn afterward. To the extent that Jupyter will smooth a lot of the wrinkles that came up during this workshop, I think it will help accomplish these goals.

That said, if we were to run the workshop in Jupyter then I think that the scripts given to the students ought to be restructured a bit. Ideally, they would be fairly minimal (not too many bells and whistles, such as embedded HTML and images, long Markdown cells with explanations, etcetera), so that students will still focus on listening and interacting in the class. Also, I think they should contain some already-coded examples (to be talked through and run as demos), and some sections with no or little pre-existing code along with instructional comments (where the instructors and students could live-code together to accomplish the tasks explained in the comments).

(Yes, I guess Spyder is an option to the extent that it works better than PyCharm, but I am admittedly a biased fan of the notebook format, so Jupyter's my vote.)

**Comment by rochelleterman** [comment]
Hi All,

I (strongly) vote for Jupyter, for many the reasons given by @drewhart. The concern about bad programming habits is putting the cart the horse. The bigger danger, to my mind, is that students leave feeling so frustrated / intimidated that they never program again. I would rather students write bad code (at least to start) than no code. 

I hear @matthew-brett 's concerns of poor habits. But the fact is, many of these students have never programmed before; their main concern is getting use to syntax, not unit testing. They need an environment that will allow them to focus on the language and feel productive. An IDE like PyCharm/Spider is distracting and intimidating, while working in the  console/text editor will be incredibly frustrating to those without a solid understanding of syntax. 

In my experience, Jupyter has served very well, especially for students without a strong programming background. The immediate positive feedback of running a cell and seeing the output is very motivating.

I recommend the Software Carpentry approach: Use Jupyter for 9/10 of the workshop, and then teach how to write a program (in a text editor) that can be run in bash at the VERY END, once people feel comfortable with the language.

Hope this helps,
Rochelle

**Comment by henchc** [comment]
I agree with everything that has been said. I think Dillon's suggestion to use the notebooks to teach, and have them write mini-programs for the challenges in a text editor is the best way to go about this. I think Drew is also right, that we should fix up the challenges a little with less prompting (perhaps the comments alone will suffice, some of the pseudo-code moved people in the wrong direction). The first challenge task would then be their introduction to programming outside the notebook, so some extra time may be necessary for this, but otherwise I think it's the best approach.

**Comment by akokai** [comment]
Good discussion. I vote for Jupyter notebook, with the following conditions:

1. Still do live coding rather than just run cells in an prepared notebook.
2. Restructure challenges and some of the teaching material to be more instructive about writing stand-alone code (following suggestion of @deniederhut and others). 

I second everyone's comments about working students up to the level of using a decent text editor, the Python console, and their command shell, at least for the peak/culminating moments. Whatever advantage IDEs have over this set of tools (for students at least) would be provided by Jupyter.

Now that I have played a bit with Spyder too, I can comment on all the options...

- **Jupyter notebook:** True, it abstracts away some relevant and important aspects of Python, which then need to be taught separately. But as @rochelleterman said it can help people get off the ground. And it does this without too much ['excise'](http://architectingusability.com/2012/07/03/dont-make-me-think-eliminating-excise-and-reducing-cognitive-load/) – as @drewhart says it's lightweight and easy to learn.
Also, importantly, there are valid professional use cases for notebooks, are there not? The output display, plotting, and interactive widgets can be pretty useful.

- **Spyder:** Some cool features, definitely a feasible alternative to Jupyter. Looks and feels kind of, um, esoteric though. Still requires learning & getting used to, and I'm not convinced that it's worth training students to deal with its idiosyncrasies.

- **PyCharm:** Seems like a very powerful IDE for those who need it. It's obviously meant for more complex projects. Way overkill for what we're doing, though! I have already uninstalled it because I hate the UI behaviour and the amount of effort it takes to make it usable.

**Comment by matthew-brett** [comment]
I should say that I have used IPython / Jupyter notebooks a lot, especially for teaching.  Noticing the problems they cause, both for the author and the reader, I have rewritten nearly all my teaching material in Sphinx.

I was alarmed to see that the student who had seemed most committed to my recent course, was still using notebooks for her daily work.

It's very hard to kick the notebook habit, once you have it.  I was lucky that I had had many years of productive programming before I found the notebook, but even so it took me a while to realize the serious downsides.  I suspect that the students will see lots of people using notebooks, it will take them a long time to notice that most experienced programmers prefer text editors and the console for their daily work, and even longer to find out why.

Students new to a field tend to assume you are teaching them best practice, especially at college level, even if it is an introductory class.

**Comment by deniederhut** [comment]
Thanks for all the comments. The consensus that I see forming is that we want to strike a balance between being accessible and emulating good coding habits.  Jupyter, although it does have drawbacks, is less painful to get running than any IDE we've tried while still allowing students to take notes alongside a fast REPL for live coding and exploration.

For the next workshop series, I conclude that we should beta:

1. Jupyter notebooks for the live coding sections of the class
2. Reframing the pytest challenges to be writing/debugging python programs
